### ISSUE TITLE
Crashing at startup due to mixin error

### ISSUE THREAD

**Issue by LoganTheOverlord** [MrSypz/ModBugReport#5]
### Confirmations

- [x] I can verify that I am running the mod on the latest possible Minecraft version.
- [X] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.1.2

### A description of the issue

There is probably some major incompatibility between mods crashing - raknetify, debugify, polymorph, C2ME and others.
I have updated the mod right now, and it's not working. The version 1.1.1 is working.

### Log or crash report

https://gist.github.com/LoganTheOverlord/4e565c3ef8cc372f652eb0a470687675

**Comment by LoganTheOverlord** [comment]
Hey, I just want to let you know that crital is really nice mod. If you can't fix the issues, maybe let me contribute a bit. I could fix the issues, maybe.

**Comment by MrSypz** [comment]
> Hey, I just want to let you know that crital is really nice mod. If you can't fix the issues, maybe let me contribute a bit. I could fix the issues, maybe.

on the 1.1.2 I forgot to delete the unused mixin that cuz the crash I already upload 1.1.3
I hope it not crash this time I guess the problem is when apply a random stats on mobs make a game crash
if you use the old version disable that config but on the newer version I already remove that mixin idk why it crash by the way

**Comment by MrSypz** [comment]
I guess the older version of it from the config **entityItemModifier**

**Comment by Y-Onell** [comment]
> Hey, I just want to let you know that crital is really nice mod. If you can't fix the issues, maybe let me contribute a bit. I could fix the issues, maybe.

FR, Dev, I admire your work and understand your reasoning, but you're sitting on two mods with amazing potential (this and penomior). Would be great to let this guy or someone else continue development/do approved backports to something like 1.20.1 if you're gonna archive such,

**Comment by LoganTheOverlord** [comment]
Yeah, the mod looks fabulous. I love how the tooltips look, and how the system works.
I have noticed though it might be interfering with damage from other attribute mods like reforged.

**Comment by MrSypz** [comment]
> > Hey, I just want to let you know that crital is really nice mod. If you can't fix the issues, maybe let me contribute a bit. I could fix the issues, maybe.
> 
> FR, Dev, I admire your work and understand your reasoning, but you're sitting on two mods with amazing potential (this and penomior). Would be great to let this guy or someone else continue development/do approved backports to something like 1.20.1 if you're gonna archive such,

crital I write it since 1.20.1 but it use triedz data pack to make it work
