### ISSUE TITLE
(Mod name)emeralds

### ISSUE THREAD

**Issue by Amras27** [MrSypz/ModBugReport#7]
When you buy an item from a merchant and you earn emeralds, they also take stats that prevent you from stacking them. Why they have stats ?

**Comment by MrSypz** [comment]
Mod?

**Comment by Amras27** [comment]
Yes for fabric 1.21

**Comment by MrSypz** [comment]
Which one?

**Comment by Amras27** [comment]
Crital

**Comment by MrSypz** [comment]
fix

**Comment by Amras27** [comment]
Great .. thk you so much .. i can reinstall This great mod
